name: .NET Core Ubuntu

on: [pull_request, push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup minikube
      uses: medyagh/setup-minikube@master
        
    - name: Init cluster
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        cd tests/minikuber
        kubectl create namespace pulsartest
        kubectl apply -f . -n pulsartest

#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 3.1.100

#     - name: Install dotnet tools locally
#       run: dotnet tool restore

#     - name: Paket Install
#       run: dotnet paket install
    
#     - name: Dotnet Restore
#       run: dotnet restore
    
#     - name: Dotnet Build Release
#       run: dotnet build -c Release --no-restore
    
#     - name: Apt-get Install Snappy & ZSTD
#       run: |
#         sudo apt-get install -y libsnappy-dev
#         sudo apt-get install -y libzstd-dev
    
#     - name: Run Unit Tests
#       run: |
#         cd tests/UnitTests
#         dotnet run -c Release --no-build

    - name: Check $MINIKUBE_IP
      run: |
        minikube ip
        export MINIKUBE_IP=$(minikube ip)
        echo $MINIKUBE_IP
        tests/compose/standalone/scripts/wait-for-it.sh $MINIKUBE_IP:30001 -t 120 -- kubectl get pod -n pulsartest

    - name: kubectl status
      run: |
        kubectl get pod -n pulsartest

#    - name: Run Integration Tests
#      timeout-minutes: 2
#      run: |
#        cd tests/IntegrationTests
#        dotnet run --no-spinner --debug
