name: .NET Core Ubuntu

on: [pull_request, push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup minikube
      uses: opsgang/ga-setup-minikube@v0.1.1
      with:
        minikube-version: 1.4.0
        k8s-version: 1.15.1
        
    - name: Init cluster
      run: |
        minikube config set vm-driver docker
        minikube config set kubernetes-version v1.15.1
        minikube start
        minikube update-context
        kubectl cluster-info
        kubectl get pods -n kube-system
        minikube ip
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Install dotnet tools locally
      run: dotnet tool restore

    - name: Paket Install
      run: dotnet paket install
    
    - name: Dotnet Restore
      run: dotnet restore
    
    - name: Dotnet Build Release
      run: dotnet build -c Release --no-restore
    
    - name: Apt-get Install Snappy & ZSTD
      run: |
        sudo apt-get install -y libsnappy-dev
        sudo apt-get install -y libzstd-dev
    
    - name: Run Unit Tests
      run: |
        cd tests/UnitTests
        dotnet run -c Release --no-build

#    - name: docker-compose status
#      run: |
#        cd tests/compose/standalone
#        docker-compose ps
#        docker-compose logs init

#    - name: Run Integration Tests
#      timeout-minutes: 2
#      run: |
#        cd tests/IntegrationTests
#        dotnet run --no-spinner --debug
